# -------------------------
# Block 2: pay4partner = False → contract_type = null
# -------------------------
- with_message_history: false
  pay4partner: false
  contract_type: null
  fog_of_war: [false, false]
  selfish: [true, true]  # Options: [false, false] (both default), [true, true] (both selfish)

# -------------------------
# Block 3: pay4partner = False → contract_type = strict
# -------------------------
- with_message_history: false
  pay4partner: false
  contract_type: strict
  fog_of_war: [false, false]
  selfish: [true, true]  # Options: [false, false] (both default), [true, true] (both selfish)

- with_message_history: false
  pay4partner: false
  contract_type: contract_for_finishing
  fog_of_war: [ false, false ]
  selfish: [ true, true ]
