grid_size: 6
colors:
  - R
  - B
  - G
grid:
  - [G, R, R, B, B, B]
  - [R, R, B, R, B, R]
  - [B, R, B, R, B, B]
  - [R, R, R, R, R, B]
  - [B, B, B, B, R, R]
  - [R, B, B, R, B, G]
resource_mode: manual
manual_resources:
  - R: 25
    G: 2
  - B: 25
    G: 2